builder:
  track: dev

labels:
  app-group: estafette-ci
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 1

stages:
  build:
    image: golang:1.13.4-alpine3.10
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOGC: off
    commands:
    - go vet ./...
    - go test -failfast -vet=off ./...
    - go build -a -installsuffix cgo -ldflags "-X cmd.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X cmd.app=${ESTAFETTE_GIT_NAME} -X cmd.version=${ESTAFETTE_BUILD_VERSION} -X cmd.revision=${ESTAFETTE_GIT_REVISION} -X cmd.branch=${ESTAFETTE_GIT_BRANCH} -X cmd.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./binaries/estafette ./estafette

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'