builder:
  track: dev

labels:
  app-group: estafette-ci
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 1
    patch: 0
    labelTemplate: '{{branch}}-{{auto}}'
    releaseBranch: 0.1.0

stages:
  build:
    image: golang:1.13.4-alpine3.10
    env:
      CGO_ENABLED: 0
      GOGC: off
    commands:
    - go vet ./...
    - go test -failfast -vet=off ./...
    - GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags "-X cmd.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X cmd.app=${ESTAFETTE_GIT_NAME} -X cmd.version=${ESTAFETTE_BUILD_VERSION} -X cmd.revision=${ESTAFETTE_GIT_REVISION} -X cmd.branch=${ESTAFETTE_GIT_BRANCH} -X cmd.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./binaries/${ESTAFETTE_GIT_NAME}-v${ESTAFETTE_BUILD_VERSION}-linux-amd64 .
    - GOOS=windows GOARCH=amd64 go build -a -installsuffix cgo -ldflags "-X cmd.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X cmd.app=${ESTAFETTE_GIT_NAME} -X cmd.version=${ESTAFETTE_BUILD_VERSION} -X cmd.revision=${ESTAFETTE_GIT_REVISION} -X cmd.branch=${ESTAFETTE_GIT_BRANCH} -X cmd.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./binaries/${ESTAFETTE_GIT_NAME}-v${ESTAFETTE_BUILD_VERSION}-windows-amd64.exe .
    - GOOS=darwin GOARCH=amd64 go build -a -installsuffix cgo -ldflags "-X cmd.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X cmd.app=${ESTAFETTE_GIT_NAME} -X cmd.version=${ESTAFETTE_BUILD_VERSION} -X cmd.revision=${ESTAFETTE_GIT_REVISION} -X cmd.branch=${ESTAFETTE_GIT_BRANCH} -X cmd.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./binaries/${ESTAFETTE_GIT_NAME}-v${ESTAFETTE_BUILD_VERSION}-darwin-amd64 .

  create-github-release:
    image: extensions/github-release:dev
    ignoreMissingMilestone: true
    prerelease: true
    assets:
    - ./binaries/${ESTAFETTE_GIT_NAME}-v${ESTAFETTE_BUILD_VERSION}-linux-amd64
    - ./binaries/${ESTAFETTE_GIT_NAME}-v${ESTAFETTE_BUILD_VERSION}-windows-amd64.exe
    - ./binaries/${ESTAFETTE_GIT_NAME}-v${ESTAFETTE_BUILD_VERSION}-darwin-amd64

  clone-tap:
    image: extensions/git-clone:dev
    repo: homebrew-tap

  create-brew-formula:
    image: extensions/brew:dev
    formula: estafette-dev
    description: The CLI for Estafette - The resilient and cloud-native CI/CD platform
    homepage: https://estafette.io
    binaryURL: https://github.com/estafette/estafette/releases/download/v${ESTAFETTE_BUILD_VERSION}/estafette-v${ESTAFETTE_BUILD_VERSION}-darwin-amd64.zip
    tapRepoDir: homebrew-tap
    formulaDir: Formula

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  github-release:
    clone: true
    stages:
      build:
        image: golang:1.13.4-alpine3.10
        env:
          CGO_ENABLED: 0
          GOGC: off
        commands:
        - GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags "-X cmd.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X cmd.app=${ESTAFETTE_GIT_NAME} -X cmd.version=${ESTAFETTE_BUILD_VERSION} -X cmd.revision=${ESTAFETTE_GIT_REVISION} -X cmd.branch=${ESTAFETTE_GIT_BRANCH} -X cmd.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./binaries/${ESTAFETTE_GIT_NAME}-v${ESTAFETTE_BUILD_VERSION}-linux-amd64 .
        - GOOS=windows GOARCH=amd64 go build -a -installsuffix cgo -ldflags "-X cmd.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X cmd.app=${ESTAFETTE_GIT_NAME} -X cmd.version=${ESTAFETTE_BUILD_VERSION} -X cmd.revision=${ESTAFETTE_GIT_REVISION} -X cmd.branch=${ESTAFETTE_GIT_BRANCH} -X cmd.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./binaries/${ESTAFETTE_GIT_NAME}-v${ESTAFETTE_BUILD_VERSION}-windows-amd64.exe .
        - GOOS=darwin GOARCH=amd64 go build -a -installsuffix cgo -ldflags "-X cmd.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X cmd.app=${ESTAFETTE_GIT_NAME} -X cmd.version=${ESTAFETTE_BUILD_VERSION} -X cmd.revision=${ESTAFETTE_GIT_REVISION} -X cmd.branch=${ESTAFETTE_GIT_BRANCH} -X cmd.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./binaries/${ESTAFETTE_GIT_NAME}-v${ESTAFETTE_BUILD_VERSION}-darwin-amd64 .

      create-github-release:
        image: extensions/github-release:dev
        ignoreMissingMilestone: true
        draft: false
        prerelease: true
        assets:
        - ./binaries/${ESTAFETTE_GIT_NAME}-v${ESTAFETTE_BUILD_VERSION}-linux-amd64
        - ./binaries/${ESTAFETTE_GIT_NAME}-v${ESTAFETTE_BUILD_VERSION}-windows-amd64.exe
        - ./binaries/${ESTAFETTE_GIT_NAME}-v${ESTAFETTE_BUILD_VERSION}-darwin-amd64